#!/usr/bin/perl
###########################################################################
# *  * Copyright 2015, Freescale Semiconductor, Inc. All rights reserved. #
###########################################################################

###########################################################################
#file: timerCtrl.sh							  #
#This script is executed by strongswan init script to ADD/DEL connections #
#  from timer module.                                                     #
###########################################################################

use IO::Socket::UNIX;

$num_args = $#ARGV + 1;
if ($num_args != 1) {
    print "Usage: timerCtrl <+/-><connection-name>\n";
    print "	<+><connection-name> : is to Add the connection to timer module.\n";
    print "	<-><connection-name> : is to Delete the connection from timer module.\n";
    exit;
}

#print "$ARGV[0]";
# flush after every write
$| = 1;

my ($socket,$data);
my $SOCK_PATH = "/tmp/.vpntimersock";

#  We call IO::Socket::UNIX->new() to create the UDP Socket
# and bind with the PeerAddr.
$socket = new IO::Socket::UNIX (
	Peer   => $SOCK_PATH,
	Type 	=> SOCK_DGRAM,
) or die "ERROR in Socket Creation : $!\n";

#send operation
$data = $ARGV[0];
$socket->send($data);

$socket->close();
