#!/bin/sh
# This script is executed as part of the hotplug event with
# HOTPLUG_TYPE=iface, triggered by various scripts when an interface
# is configured (ACTION=ifup) or deconfigured (ACTION=ifdown).  The
# interface is available as INTERFACE, the real device as DEVICE.

. /lib/functions/network.sh

[ "$ACTION" == "rtupd" ] && exit 0
[ "$DEVICE" == "lo" ] && exit 0

isvlan=$(echo $INTERFACE | grep vlan)
[ -n "$isvlan" ] && exit 0

                 
case "$ACTION" in
	ifup)
		local wan_status=`echo $INTERFACE | grep -E "^wan.*|^usb.*|^gre.*"`
		if [ "$wan_status" != ""  ]                      
		then
			lcsh sys stop 2>&- >&-
			network_get_waniface device $INTERFACE 
			logger -t button-hotpg-lionic Device: $device   $INTERFACE/ Action: $ACTION

			# Adding WAN to Lionic DPI modules
			lcsh iface wan set $device
			lcsh ips psd watch add $device
			lcsh sys wan $device 2>&- >&-

			lcsh sys start 2>&- >&-
		fi                                                                                 
	;;

	ifdown)
		lcsh sys stop 2>&- >&-
		logger -t button-hotpg-lionic Device: $device   $INTERFACE/ Action: $ACTION
		lcsh sys start 2>&- >&-
	;;
esac
